### ISSUE TITLE
Alamofire 4.0.0-beta1 support

### ISSUE THREAD

**Issue by Tulleb** [tristanhimmelman/AlamofireObjectMapper#127]
```
- `Alamofire (from `https://github.com/Alamofire/Alamofire.git`, branch `swift3`)` required by `Podfile`
- `Alamofire (= 4.0.0)` required by `Podfile.lock`
- `Alamofire (~> 3.2)` required by `AlamofireObjectMapper (3.0.0)`
```

I am using the `swift-3` branch but I'm quite sure it is the same with the `master` branch.

**Comment by carobeta** [comment]
I have the same problem, could you fix it?

**Comment by Tulleb** [comment]
Even if @tristanhimmelman solved it, the ObjectMapper library is not supporting Xcode8b6 yet. So we just have to wait or submit a PR over there I guess :)

**Comment by Urkman** [comment]
ObjectMapper is updates for Beta6 now...

**Comment by Tulleb** [comment]
Yes that's why I also opened #128...

**Comment by Urkman** [comment]
There is already a PR...

**Comment by reza355** [comment]
so is it works now? i tried to install in xcode 8 beta 6 today and xcode still asking to convert code from swift 2 to 3 :| . i download from 'swift3' branch..

**Comment by tfannon** [comment]
So,  I am confused.  Other issues which reference this problem have been closed. 
@tristanhimmelman said he merged another pull request, but that dealt with Beta 6, not this dependency.

So, from what I can see,  this swift-3 branch is still not compatible with alamofire's swift-3 branch?

_pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3'
pod 'AlamofireObjectMapper', :git => 'https://github.com/tristanhimmelman/AlamofireObjectMapper.git', :branch => 'swift-3'_


Sorry if I am asking something already answered.  

Is there a way to manually resolve this?

**Comment by Tulleb** [comment]
@tfannon everything should be working once @tristanhimmelman will merge #130.

**Comment by tfannon** [comment]
@Tulleb .  Looks like it was working until the most recent commit in Alamofire branch.

**Comment by reza355** [comment]
@tfannon agree... i've got 94 error in manager.swift

**Comment by tfannon** [comment]
@reza355   well.. i think that is a mistake on the alamofire team's part.  i had to delete the manager class  ( if you look at the branch, it is not included in the source, yet it IS in the cocoapod).  

regardless, even with manager gone,  the alamofireobjectmapper still doesn't compile yet.

cheers!  here's to when swift 3.0 stops changing :)

**Comment by Tulleb** [comment]
@tfannon,  @reza355,
The pull request #129 merged by @tristanhimmelman is just **bad** and **incomplete**.

If you are using the _swift-3_ branch, here are the 2 solutions you have at the moment:

- **NOT WORKING**: You can wait for @tristanhimmelman to reverse #129 commits and merge #130 instead,

- **WORKING**: You can replace your AlamofireObjectMapper pod line from your Podfile by this one:
`  pod 'AlamofireObjectMapper', :git => 'https://github.com/bdbergeron/AlamofireObjectMapper.git', :branch => 'swift-3'`
And go back to the original line you had when @tristanhimmelman will merge #130.

**Comment by Tulleb** [comment]
Fixed by #130.
